language: node_js
node_js:
  - "10.7.0"

script:
  # run linter and check to make sure TypeScript can build the source code
  - npm test

before_deploy:
  # build the docs for the API
  - npm run docs
  # file to tell GitHub pages not to try to run jekyll stuff (can break urls)
  - touch temp/docs/.nojekyll
  # prepare directory for npm and gh-pages deploy
  - npm run pre:pack
  - npm pack

deploy:
  - provider: pages
    skip-cleanup: true
    verbose: true
    local-dir: temp/docs/
    github-token: $GH_TOKEN
    on:
      branch: master

  - provider: releases
    api_key: $GH_TOKEN
    skip_cleanup: true
    file_glob: true
    file: "cadre-ts-utils-*.tgz"
    on:
      tags: true

  - provider: npm
    api_key: $NPM_TOKEN
    skip_cleanup: true
    email: "jacob.t.fischer@gmail.com"
    on:
      tags: true
